auth:
  postgresPassword: "mysecurepassword"
primary:
  initdb:
    scripts:
      my_init.sql: |
        CREATE DATABASE n8n;
        CREATE DATABASE onedev;
        CREATE DATABASE zabbix;
        CREATE DATABASE openwebui;
        CREATE DATABASE openwebuipgvector;
        CREATE DATABASE keycloak;
  service:
    type: LoadBalancer
