ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: "chatwoot.uaiso.lan"
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: uaiso-chatwoot
              port:
                number: 3000
services:
  type: ClusterIP
