ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: "chatwoot.uaiso.lan"
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: chatwoot
              port:
                number: 3000
services:
  name: chatwoot
  internalPort: 3000
  targetPort: 3000
  type: ClusterIP
